# Generated by Django 3.2 on 2021-04-30 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('GPU', 'Graphics Card'), ('CPU', 'Processor'), ('PSU', 'Power Supply'), ('MTB', 'Motherboard'), ('MEM', 'Memory'), ('STR', 'Storage'), ('CASE', 'Case'), ('OTR', 'Other')], default=None, max_length=32)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcBB.device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcBB.location'),
        ),
    ]
