# Generated by Django 3.2 on 2021-04-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcBB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='device',
        ),
        migrations.RemoveField(
            model_name='device',
            name='description',
        ),
        migrations.RemoveField(
            model_name='device',
            name='location',
        ),
        migrations.AddField(
            model_name='device',
            name='asset_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='customer_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='motherboard_brand',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='motherboard_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='motherboard_serial',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='pc_cpu',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='pc_gpu',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='pc_hd',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='pc_os',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='pc_ram',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='pc_service_tag',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='pc_user',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='pc_windows_key',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
    ]
