# Generated by Django 3.2 on 2021-04-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcBB', '0003_auto_20210430_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
