# Generated by Django 3.2 on 2021-05-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcBB', '0004_device_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='asset_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='customer_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='pc_windows_key',
            field=models.CharField(blank=True, default='None', max_length=255),
        ),
    ]
