# Generated by Django 3.2 on 2021-05-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcBB', '0005_auto_20210430_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='pc_windows_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
