# Generated by Django 3.2 on 2021-05-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcBB', '0006_alter_device_pc_windows_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, default='Test', max_length=255),
        ),
    ]
