# Generated by Django 3.2 on 2021-05-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcBB', '0007_alter_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
